#!/usr/bin/env python3

"""
filter incoming lines based on date threshold

hides tasks marked with a date threshold ("t:YYYY-MM-DD") in the future

this is intended to be used as TODOTXT_FINAL_FILTER
"""

import re
import sys
from datetime import datetime
from functools import partial


def threshold_not_after(date: datetime, task: str) -> bool:
    """ Only allow tasks who don't have a future threshold """
    pattern = re.compile(r"t:(\d{4})-(\d{2})-(\d{2})")
    match = pattern.search(task)
    if match:
        threshold = [int(i) for i in match.groups()]
        if datetime(*threshold) > date:
            return False
    return True


def has_pri(task: str) -> bool:
    maybe_pri = task.split()[1]
    pattern = re.compile(r'\([A-Z]\)')
    return bool(pattern.match(maybe_pri))


def main(args=None):
    tasks = filter(partial(threshold_not_after, datetime.now()), sys.stdin)
    tasks = filter(has_pri, tasks)
    [print(t.strip()) for t in tasks]
    return True


if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
